version: '3.8'

services:
  backend:
    image: example-backend:1.14
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=cache
  frontend:
    image: example-frontend:1.14
    ports:
      - 5000:5000
  redis:
    image: redis:7.0.9
    container_name: cache
