version: '3.9'

services:
  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: db
  backend:
    image: example-backend:1.14
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=cache
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  frontend:
    image: example-frontend:1.14
    ports:
      - 5000:5000
  redis:
    image: redis:7.0.9
    container_name: cache
